const bankList = [
  {
    "code": "CCB",
    "name": "中国建设银行"
  }, {
    "code": "ICBC",
    "name": "中国工商银行"
  }, {
    "code": "ABC",
    "name": "中国农业银行"
  }, {
    "code": "PSBC",
    "name": "中国邮政储蓄银行"
  }, {
    "code": "CMB",
    "name": "招商银行"
  }, {
    "code": "BOC",
    "name": "中国银行"
  }, {
    "code": "CITIC",
    "name": "中信银行"
  }, {
    "code": "HXBANK",
    "name": "华夏银行"
  }, {
    "code": "SPABANK",
    "name": "平安银行"
  }, {
    "code": "BJBANK",
    "name": "北京银行"
  }, {
    "code": "SRCB",
    "name": "深圳农村商业银行"
  }, {
    "code": "BGB",
    "name": "广西北部湾银行"
  }, {
    "code": "SHRCB",
    "name": "上海农村商业银行"
  }, {
    "code": "WHCCB",
    "name": "威海市商业银行"
  }, {
    "code": "BOZK",
    "name": "周口银行"
  }, {
    "code": "KORLABANK",
    "name": "库尔勒市商业银行"
  }, {
    "code": "SDEB",
    "name": "顺德农商银行"
  }, {
    "code": "HURCB",
    "name": "湖北省农村信用社"
  }, {
    "code": "WRCB",
    "name": "无锡农村商业银行"
  }, {
    "code": "BOCY",
    "name": "朝阳银行"
  }, {
    "code": "CZBANK",
    "name": "浙商银行"
  }, {
    "code": "HDBANK",
    "name": "邯郸银行"
  }, {
    "code": "BOD",
    "name": "东莞银行"
  }, {
    "code": "ZYCBANK",
    "name": "遵义市商业银行"
  }, {
    "code": "SXCB",
    "name": "绍兴银行"
  }, {
    "code": "GZRCU",
    "name": "贵州省农村信用社"
  }, {
    "code": "ZJKCCB",
    "name": "张家口市商业银行"
  }, {
    "code": "BOJZ",
    "name": "锦州银行"
  }, {
    "code": "BOP",
    "name": "平顶山银行"
  }, {
    "code": "HKB",
    "name": "汉口银行"
  }, {
    "code": "SPDB",
    "name": "上海浦东发展银行"
  }, {
    "code": "NXRCU",
    "name": "宁夏黄河农村商业银行"
  }, {
    "code": "NYNB",
    "name": "广东南粤银行"
  }, {
    "code": "GRCB",
    "name": "广州农商银行"
  }, {
    "code": "BOSZ",
    "name": "苏州银行"
  }, {
    "code": "HZCB",
    "name": "杭州银行"
  }, {
    "code": "HSBK",
    "name": "衡水银行"
  }, {
    "code": "HBC",
    "name": "湖北银行"
  }, {
    "code": "JXBANK",
    "name": "嘉兴银行"
  }, {
    "code": "HRXJB",
    "name": "华融湘江银行"
  }, {
    "code": "BODD",
    "name": "丹东银行"
  }, {
    "code": "AYCB",
    "name": "安阳银行"
  }, {
    "code": "EGBANK",
    "name": "恒丰银行"
  }, {
    "code": "CDB",
    "name": "国家开发银行"
  }, {
    "code": "TCRCB",
    "name": "江苏太仓农村商业银行"
  }, {
    "code": "NJCB",
    "name": "南京银行"
  }, {
    "code": "ZZBANK",
    "name": "郑州银行"
  }, {
    "code": "DYCB",
    "name": "德阳商业银行"
  }, {
    "code": "YBCCB",
    "name": "宜宾市商业银行"
  }, {
    "code": "SCRCU",
    "name": "四川省农村信用"
  }, {
    "code": "KLB",
    "name": "昆仑银行"
  }, {
    "code": "LSBANK",
    "name": "莱商银行"
  }, {
    "code": "YDRCB",
    "name": "尧都农商行"
  }, {
    "code": "CCQTGB",
    "name": "重庆三峡银行"
  }, {
    "code": "FDB",
    "name": "富滇银行"
  }, {
    "code": "JSRCU",
    "name": "江苏省农村信用联合社"
  }, {
    "code": "JNBANK",
    "name": "济宁银行"
  }, {
    "code": "JINCHB",
    "name": "晋城银行"
  }, {
    "code": "FXCB",
    "name": "阜新银行"
  }, {
    "code": "WHRCB",
    "name": "武汉农村商业银行"
  }, {
    "code": "HBYCBANK",
    "name": "湖北银行宜昌分行"
  }, {
    "code": "TZCB",
    "name": "台州银行"
  }, {
    "code": "TACCB",
    "name": "泰安市商业银行"
  }, {
    "code": "XCYH",
    "name": "许昌银行"
  }, {
    "code": "CEB",
    "name": "中国光大银行"
  }, {
    "code": "NXBANK",
    "name": "宁夏银行"
  }, {
    "code": "HSBANK",
    "name": "徽商银行"
  }, {
    "code": "JJBANK",
    "name": "九江银行"
  }, {
    "code": "NHQS",
    "name": "农信银清算中心"
  }, {
    "code": "MTBANK",
    "name": "浙江民泰商业银行"
  }, {
    "code": "LANGFB",
    "name": "廊坊银行"
  }, {
    "code": "ASCB",
    "name": "鞍山银行"
  }, {
    "code": "KSRB",
    "name": "昆山农村商业银行"
  }, {
    "code": "YXCCB",
    "name": "玉溪市商业银行"
  }, {
    "code": "DLB",
    "name": "大连银行"
  }, {
    "code": "DRCBCL",
    "name": "东莞农村商业银行"
  }, {
    "code": "GCB",
    "name": "广州银行"
  }, {
    "code": "NBBANK",
    "name": "宁波银行"
  }, {
    "code": "BOYK",
    "name": "营口银行"
  }, {
    "code": "SXRCCU",
    "name": "陕西信合"
  }, {
    "code": "GLBANK",
    "name": "桂林银行"
  }, {
    "code": "BOQH",
    "name": "青海银行"
  }, {
    "code": "CDRCB",
    "name": "成都农商银行"
  }, {
    "code": "QDCCB",
    "name": "青岛银行"
  }, {
    "code": "HKBEA",
    "name": "东亚银行"
  }, {
    "code": "HBHSBANK",
    "name": "湖北银行黄石分行"
  }, {
    "code": "WZCB",
    "name": "温州银行"
  }, {
    "code": "TRCB",
    "name": "天津农商银行"
  }, {
    "code": "QLBANK",
    "name": "齐鲁银行"
  }, {
    "code": "GDRCC",
    "name": "广东省农村信用社联合社"
  }, {
    "code": "ZJTLCB",
    "name": "浙江泰隆商业银行"
  }, {
    "code": "GZB",
    "name": "赣州银行"
  }, {
    "code": "GYCB",
    "name": "贵阳市商业银行"
  }, {
    "code": "CQBANK",
    "name": "重庆银行"
  }, {
    "code": "DAQINGB",
    "name": "龙江银行"
  }, {
    "code": "CGNB",
    "name": "南充市商业银行"
  }, {
    "code": "SCCB",
    "name": "三门峡银行"
  }, {
    "code": "CSRCB",
    "name": "常熟农村商业银行"
  }, {
    "code": "SHBANK",
    "name": "上海银行"
  }, {
    "code": "JLBANK",
    "name": "吉林银行"
  }, {
    "code": "CZRCB",
    "name": "常州农村信用联社"
  }, {
    "code": "BANKWF",
    "name": "潍坊银行"
  }, {
    "code": "ZRCBANK",
    "name": "张家港农村商业银行"
  }, {
    "code": "FJHXBC",
    "name": "福建海峡银行"
  }, {
    "code": "ZJNX",
    "name": "浙江省农村信用社联合社"
  }, {
    "code": "LZYH",
    "name": "兰州银行"
  }, {
    "code": "JSB",
    "name": "晋商银行"
  }, {
    "code": "BOHAIB",
    "name": "渤海银行"
  }, {
    "code": "CZCB",
    "name": "浙江稠州商业银行"
  }, {
    "code": "YQCCB",
    "name": "阳泉银行"
  }, {
    "code": "SJBANK",
    "name": "盛京银行"
  }, {
    "code": "XABANK",
    "name": "西安银行"
  }, {
    "code": "BSB",
    "name": "包商银行"
  }, {
    "code": "JSBANK",
    "name": "江苏银行"
  }, {
    "code": "FSCB",
    "name": "抚顺银行"
  }, {
    "code": "HNRCU",
    "name": "河南省农村信用"
  }, {
    "code": "COMM",
    "name": "交通银行"
  }, {
    "code": "XTB",
    "name": "邢台银行"
  }, {
    "code": "HNRCC",
    "name": "湖南省农村信用社"
  }, {
    "code": "DYCCB",
    "name": "东营市商业银行"
  }, {
    "code": "ORBANK",
    "name": "鄂尔多斯银行"
  }, {
    "code": "BJRCB",
    "name": "北京农村商业银行"
  }, {
    "code": "XYBANK",
    "name": "信阳银行"
  }, {
    "code": "ZGCCB",
    "name": "自贡市商业银行"
  }, {
    "code": "CDCB",
    "name": "成都银行"
  }, {
    "code": "HANABANK",
    "name": "韩亚银行"
  }, {
    "code": "CMBC",
    "name": "中国民生银行"
  }, {
    "code": "LYBANK",
    "name": "洛阳银行"
  }, {
    "code": "GDB",
    "name": "广东发展银行"
  }, {
    "code": "ZBCB",
    "name": "齐商银行"
  }, {
    "code": "CBKF",
    "name": "开封市商业银行"
  }, {
    "code": "H3CB",
    "name": "内蒙古银行"
  }, {
    "code": "CIB",
    "name": "兴业银行"
  }, {
    "code": "CRCBANK",
    "name": "重庆农村商业银行"
  }, {
    "code": "SZSBK",
    "name": "石嘴山银行"
  }, {
    "code": "DZBANK",
    "name": "德州银行"
  }, {
    "code": "SRBANK",
    "name": "上饶银行"
  }, {
    "code": "LSCCB",
    "name": "乐山市商业银行"
  }, {
    "code": "JXRCU",
    "name": "江西省农村信用"
  }, {
    "code": "JZBANK",
    "name": "晋中市商业银行"
  }, {
    "code": "HZCCB",
    "name": "湖州市商业银行"
  }, {
    "code": "NHB",
    "name": "南海农村信用联社"
  }, {
    "code": "XXBANK",
    "name": "新乡银行"
  }, {
    "code": "JRCB",
    "name": "江苏江阴农村商业银行"
  }, {
    "code": "YNRCC",
    "name": "云南省农村信用社"
  }, {
    "code": "GXRCU",
    "name": "广西省农村信用"
  }, {
    "code": "BZMD",
    "name": "驻马店银行"
  }, {
    "code": "ARCU",
    "name": "安徽省农村信用社"
  }, {
    "code": "GSRCU",
    "name": "甘肃省农村信用"
  }, {
    "code": "LYCB",
    "name": "辽阳市商业银行"
  }, {
    "code": "JLRCU",
    "name": "吉林农信"
  }, {
    "code": "URMQCCB",
    "name": "乌鲁木齐市商业银行"
  }, {
    "code": "XLBANK",
    "name": "中山小榄村镇银行"
  }, {
    "code": "CSCB",
    "name": "长沙银行"
  }, {
    "code": "JHBANK",
    "name": "金华银行"
  }, {
    "code": "BHB",
    "name": "河北银行"
  }, {
    "code": "NBYZ",
    "name": "鄞州银行"
  }, {
    "code": "LSBC",
    "name": "临商银行"
  }, {
    "code": "BOCD",
    "name": "承德银行"
  }, {
    "code": "SDRCU",
    "name": "山东农信"
  }, {
    "code": "NCB",
    "name": "南昌银行"
  }, {
    "code": "TCCB",
    "name": "天津银行"
  }, {
    "code": "WJRCB",
    "name": "吴江农商银行"
  }, {
    "code": "CBBQS",
    "name": "城市商业银行资金清算中心"
  }, {
    "code": "HBRCU",
    "name": "河北省农村信用社"
  }
];
export const getBankList = () => {
  return bankList;
};
export const getBankName = (code) => {
  for (let i = 0; i < bankList.length; i++) {
    if (bankList[i].code === code) {
      return bankList[i].name
    }
  }
  return '未匹配到银行';
};
